dist: trusty

language: node_js

node_js:
  - lts/*

before_script:
  - rm -rf public || exit 0

install:
  - npm install

script:
  - hexo clean
  - hexo generate
  - echo 'coldstone.fun' > public/CNAME

cache: npm

deploy:
  cleanup: true
  provider: pages
  local-dir: public
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
